### ISSUE TITLE
添加预设时，提供了足够的参数，但出现java.lang.IllegalArgumentException异常（提示参数不足）

### ISSUE THREAD

**Issue by DreamOneX** [asforest/MShell#5]
### status
```java
Running MiraiConsole v2.10.0, built on 2022-02-01 00:02:35.
Frontend Terminal: version 2.10.0, provided by Mamoe Technologies

Permission Service: Built In Permission Service

Plugins: 点歌插件 v1.1.7, MShell v0.0.0, net.mamoe.mirai-api-http v1.10.0, MCL Addon v1.2.2, Chat Command v0.5.0

Object Pending Finalization Count: 0
                 committed |  init  |  used   |   max   
    Heap Memory:  86.18MB  | 16.0MB | 56.47MB | 233.93MB
Non-Heap Memory:  82.93MB  | 7.31MB | 79.38MB |    -1   
```
### 输出
```java
> ms preset add bash utf-8 /bin/bash
2022-03-08 22:08:00 E/console: java.lang.IllegalArgumentException: Callable expects 6 arguments, but 5 were provided.
java.lang.IllegalArgumentException: Callable expects 6 arguments, but 5 were provided.
        at kotlin.reflect.jvm.internal.calls.Caller$DefaultImpls.checkArguments(Caller.kt:20)                                                                         at kotlin.reflect.jvm.internal.calls.CallerImpl.checkArguments(CallerImpl.kt:15)                                                                              at kotlin.reflect.jvm.internal.calls.CallerImpl$Method$Instance.call(CallerImpl.kt:112)                                                                       at kotlin.reflect.jvm.internal.KCallableImpl.call(KCallableImpl.kt:108)        at kotlin.reflect.full.KCallables.callSuspend(KCallables.kt:56)                at com.github.asforest.mshell.command.resolver.ArgumentedFunction.callSuspend(ArgumentedFunction.kt:29)
        at com.github.asforest.mshell.command.mshell.MShellCommand.onCommand(MShellCommand.kt:58)
        at com.github.asforest.mshell.command.MiraiTreeCommand$overloads$1.invokeSuspend(MiraiTreeCommand.kt:59)
        at com.github.asforest.mshell.command.MiraiTreeCommand$overloads$1.invoke(MiraiTreeCommand.kt)
        at com.github.asforest.mshell.command.MiraiTreeCommand$overloads$1.invoke(MiraiTreeCommand.kt)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureImpl.call$suspendImpl(CommandSignature.kt:75)
        at net.mamoe.mirai.console.command.descriptor.CommandSignatureImpl.call(CommandSignature.kt)
        at net.mamoe.mirai.console.internal.command.CommandManagerImplKt.executeCommandImpl(CommandManagerImpl.kt:167)
        at net.mamoe.mirai.console.command.CommandManager.executeCommand(CommandManager.kt:131)
        at net.mamoe.mirai.console.command.CommandManager$INSTANCE.executeCommand(CommandManager.kt)
        at net.mamoe.mirai.console.terminal.ConsoleThreadKt$startupConsoleThread$3.invokeSuspend(ConsoleThread.kt:191)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```
### 复现方式

1. 安装mcl
2. 安装chat-command，mirai-api-http插件
3. 安装MShell插件
4. 执行指令`ms preset add bash utf-8 /bin/bash`

### 个人尝试
我在发现此报错后，尝试增加，减少参数数量，减少参数后正常反馈错误，增加参数后仍然出现`java.lang.IllegalArgumentException: Callable expects 6 arguments, but 5 were provided.`

**Comment by asforest** [comment]
感谢反馈BUG，提供详细的复现方法和环境信息。这个问题是由于代码里各种情况考虑欠佳导致的，并且已在2.2.1版本中修复。（刚提交，可能需要五分钟以后等待GitHubActions打包才可以下载）
